"""Ruff-PATH-only repair for prelocked AppWorld 0.2 task generation."""
from __future__ import annotations
import argparse,hashlib,json,os,shutil,subprocess,time
from pathlib import Path
REPO_ROOT=Path(__file__).resolve().parents[1]
def R(p):
 p=Path(p);return p if p.is_absolute() else REPO_ROOT/p
def H(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def tree_hash(path):
 h=hashlib.sha256()
 for item in sorted(x for x in path.rglob('*') if x.is_file()):h.update(str(item.relative_to(path)).encode());h.update(hashlib.sha256(item.read_bytes()).digest())
 return h.hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--contract',type=Path,default=Path('specs/recurrent_parallel_appworld_generated_tasks_v2.json'));ap.add_argument('--output-dir',type=Path,default=Path('results/recurrent_parallel_appworld_generated_tasks_v2'));a=ap.parse_args();cp=R(a.contract);c=json.loads(cp.read_text());failure=json.loads(R(c['v1_failure']).read_text());source=R(c['source_root']);root=R(c['generated_root']);rebuild=json.loads(R(c['base_rebuild_status']).read_text());out=R(a.output_dir);out.mkdir(parents=True,exist_ok=True);lockp=R(c['execution_lock']);lock=json.loads(lockp.read_text());lock_checks={p:H(R(p))==v for p,v in lock['files'].items()};commit=subprocess.run(['git','rev-parse','HEAD'],cwd=source,capture_output=True,text=True,check=True).stdout.strip();pre={'contract_frozen':c['status']=='FROZEN_BEFORE_COMPLETE_GENERATED_TASK_OUTCOMES','v1_failure':failure['status']=='RPD_APPWORLD_GENERATED_TASKS_FAIL' and failure['validation_outcomes_observed']==0,'repair_scope':len(c['repair_scope'])==2,'source_commit':commit==c['source_commit'],'base_rebuild':rebuild['status']=='APPWORLD_DATA_V02_REBUILD_PASS','data_version':(root/'data/version.txt').read_text().strip()==c['data_version'],'execution_lock':lock['status']=='LOCKED_BEFORE_COMPLETE_GENERATED_TASK_OUTCOMES' and all(lock_checks.values()) and lock['contract_sha256']==H(cp),'results_absent':not (out/'generation.json').exists()}
 if not all(pre.values()):raise RuntimeError(pre)
 shutil.rmtree(root/'data/tasks',ignore_errors=True);shutil.rmtree(root/'data/datasets',ignore_errors=True);(root/'data/tasks').mkdir(parents=True);(root/'data/datasets').mkdir(parents=True);command=[str(source/'.venv/bin/python'),'-m','generate.tasks.generate_and_validate_tasks',','.join(c['generator_ids']),'--generator_num_tasks',str(c['generator_num_tasks']),'--use_environment','--use_compiled_solution','--random_seed',str(c['random_seed']),'--suppress_errors','--no_color'];env=os.environ.copy();env.update({'APPWORLD_ROOT':str(root),'PYTHONHASHSEED':str(c['python_hash_seed']),'PYTHONWARNINGS':'ignore','PATH':str(source/'.venv/bin')+os.pathsep+env.get('PATH','')});logp=out/'generation.log';t0=time.time()
 with logp.open('w') as log:process=subprocess.run(command,cwd=source,env=env,stdout=log,stderr=subprocess.STDOUT,check=False)
 rows=[]
 for gid in c['generator_ids']:
  for variation in range(1,c['generator_num_tasks']+1):
   task_id=f'{gid}_{variation}';path=root/'data/tasks'/task_id;split=next(name for name,values in c['splits'].items() if variation in values);rows.append({'task_id':task_id,'generator_id':gid,'variation':variation,'split':split,'exists':path.is_dir(),'tree_sha256':tree_hash(path) if path.is_dir() else None})
 valid_generators=sum(all(x['exists'] for x in rows if x['generator_id']==gid) for gid in c['generator_ids']);checks={**pre,'command':process.returncode==0,'cardinality':sum(x['exists'] for x in rows)==c['expected_tasks'],'valid_generators':valid_generators>=c['minimum_valid_generators'],'split_counts':all(sum(x['exists'] and x['split']==name for x in rows)==len(values)*len(c['generator_ids']) for name,values in c['splits'].items()),'protected_content_absent':all(set(x)=={'task_id','generator_id','variation','split','exists','tree_sha256'} for x in rows)};status='RPD_APPWORLD_GENERATED_TASKS_PASS' if all(checks.values()) else 'RPD_APPWORLD_GENERATED_TASKS_FAIL';mp=out/'task_manifest.json';mp.write_text(json.dumps({'schema':'recurrent_appworld_generated_task_manifest_v2','status':status,'source_commit':commit,'data_version':c['data_version'],'rows':rows},indent=2,sort_keys=True)+'\n');payload={'schema':'recurrent_appworld_generated_tasks_v2','status':status,'checks':checks,'tasks':sum(x['exists'] for x in rows),'valid_generators':valid_generators,'split_counts':{name:sum(x['exists'] and x['split']==name for x in rows) for name in c['splits']},'seconds':time.time()-t0,'execution_lock_sha256':H(lockp),'v1_failure_sha256':H(R(c['v1_failure'])),'hashes':{'contract':H(cp),'generation_log':H(logp),'manifest':H(mp),'source':H(Path(__file__))},'external_process_actions':False,'model_gpu_docker_used':False,'protected_content_exported':False,'headline_eligible':False};(out/'generation.json').write_text(json.dumps(payload,indent=2,sort_keys=True)+'\n');(out/'result_binding.json').write_text(json.dumps({'execution_lock_sha256':H(lockp),'generation_sha256':H(out/'generation.json'),'manifest_sha256':H(mp)},indent=2,sort_keys=True)+'\n');lines=['# AppWorld 0.2 Fresh Task Generation v2','',f"## Status: **`{status}`**",'',f"- Generated tasks: {payload['tasks']}/{c['expected_tasks']}",f"- Valid generators: {valid_generators}/{len(c['generator_ids'])}",f"- Split counts: {payload['split_counts']}",f"- Runtime: {payload['seconds']/60:.1f} minutes",'- External process actions: No','- Protected content exported: No','','## Checks','']+[f"- `{k}`: **{'PASS' if v else 'FAIL'}**" for k,v in checks.items()];(out/'REPORT.md').write_text('\n'.join(lines)+'\n');print(json.dumps({'status':status,'tasks':payload['tasks'],'valid_generators':valid_generators,'report':str((out/'REPORT.md').relative_to(REPO_ROOT))}))
if __name__=='__main__':main()
