"""Freeze and audit the paired AppWorld A3 prompt manifest before model outcomes."""
from __future__ import annotations
import argparse,hashlib,json,re
from collections import Counter
from pathlib import Path
REPO_ROOT=Path(__file__).resolve().parents[1]
def R(p):
 p=Path(p);return p if p.is_absolute() else REPO_ROOT/p
def H(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--contract',type=Path,default=Path('specs/recurrent_parallel_appworld_signal_anchor_v1.json'));ap.add_argument('--output-dir',type=Path,default=Path('results/recurrent_parallel_appworld_signal_anchor'));a=ap.parse_args();cp=R(a.contract);c=json.loads(cp.read_text());out=R(a.output_dir);mp=out/'prompt_manifest.json';lp=out/'adjudication_manifest.json';hp=out/'harvest.json';manifest=json.loads(mp.read_text());labels=json.loads(lp.read_text());harvest=json.loads(hp.read_text());rows=manifest['rows'];label_rows=labels['rows'];by_id={x['sample_id']:x for x in label_rows};pairs={}
 for row in rows:pairs.setdefault(row['pair_id'],[]).append(row)
 pair_context=True;pair_labels=True
 for pair_id,items in pairs.items():
  pair_context=pair_context and len(items)==2 and len({x['context_sha256'] for x in items})==1
  payloads=[json.loads(x['prompt'].splitlines()[-1]) for x in items];pair_context=pair_context and payloads[0].keys()==payloads[1].keys() and {k:payloads[0][k] for k in payloads[0] if k!='candidate_arguments'}=={k:payloads[1][k] for k in payloads[1] if k!='candidate_arguments'} and payloads[0]['candidate_arguments']!=payloads[1]['candidate_arguments'];pair_labels=pair_labels and {by_id[x['sample_id']]['label'] for x in items}=={False,True}
 forbidden=[x.lower() for x in c['forbidden_prompt_content']];forbidden_absent=all(not any(word in row['prompt'].lower() for word in forbidden) for row in rows);jwt_absent=all(not re.search(r'eyJ[A-Za-z0-9_-]{20,}',row['prompt']) for row in rows);long_card_absent=all(not re.search(r'(?<!\d)\d{13,19}(?!\d)',row['prompt']) for row in rows)
 from transformers import AutoTokenizer
 tok=AutoTokenizer.from_pretrained(c['model'],revision=c['model_revision'],local_files_only=True);formatted=[]
 for row in rows:
  messages=[{'role':'system','content':'You are a deterministic pre-commit consistency judge. Output only the exact JSON schema.'},{'role':'user','content':row['prompt']}];formatted.append(tok.apply_chat_template(messages,tokenize=False,add_generation_prompt=True,enable_thinking=c['enable_thinking']))
 tokens=[len(tok(x)['input_ids']) for x in formatted];checks={'source_complete':harvest['status']=='APPWORLD_A3_HARVEST_COMPLETE' and all(harvest['checks'].values()),'model_revision':manifest['model']==c['model'] and manifest['model_revision']==c['model_revision'],'prompt_cardinality':len(rows)==c['selection']['expected_prompts'],'pair_cardinality':len(pairs)==c['selection']['expected_pairs'],'task_types':len({x['task_type'] for x in rows})==c['selection']['expected_task_types'],'unique_ids':len({x['sample_id'] for x in rows})==len(rows),'unique_prompts':len({x['prompt_sha256'] for x in rows})==len(rows),'prompt_hash_replay':all(hashlib.sha256(x['prompt'].encode()).hexdigest()==x['prompt_sha256'] for x in rows),'exact_label_ids':set(by_id)=={x['sample_id'] for x in rows},'balanced_labels':sum(x['label'] for x in label_rows)*2==len(label_rows),'pair_context_match':pair_context,'pair_labels':pair_labels,'labels_separate':all('label' not in x for x in rows),'forbidden_absent':forbidden_absent,'jwt_absent':jwt_absent,'long_card_absent':long_card_absent,'input_token_cap':max(tokens)<=c['max_input_tokens'],'protected_local_only':manifest.get('protected_local_only') is True};status=c['verdicts']['ready'] if all(checks.values()) else c['verdicts']['protocol']
 lock_paths=['specs/recurrent_parallel_appworld_signal_anchor_v1.md','specs/recurrent_parallel_appworld_signal_anchor_v1.json','results/recurrent_parallel_appworld_controller_a2/analysis.json','results/recurrent_parallel_appworld_controller_a2/execution_lock.json','results/recurrent_parallel_appworld_semantic_mutation_development/results.json','results/model_download/qwen3_5_4b/qwen_download.json','experiments/appworld_trace_replay.py','analysis/recurrent_appworld_a3_harvest.py','analysis/recurrent_appworld_a3_manifest_audit.py','analysis/recurrent_appworld_a3_run.py','analysis/recurrent_appworld_a3_analysis.py'];lock={'schema':'recurrent_appworld_a3_execution_lock_v1','status':'LOCKED_BEFORE_MODEL_OUTCOMES','files':{p:H(R(p)) for p in lock_paths},'prompt_manifest':{'path':str(mp.relative_to(REPO_ROOT)),'sha256':H(mp)},'adjudication_manifest':{'path':str(lp.relative_to(REPO_ROOT)),'sha256':H(lp)},'harvest_sha256':H(hp),'model':c['model'],'model_revision':c['model_revision']};ep=out/'execution_lock.json';ep.write_text(json.dumps(lock,indent=2,sort_keys=True)+'\n');payload={'schema':'recurrent_appworld_a3_manifest_audit_v1','status':status,'checks':checks,'pairs':len(pairs),'prompts':len(rows),'task_types':len({x['task_type'] for x in rows}),'task_type_pair_counts':dict(sorted(Counter(x['task_type'] for x in label_rows if x['label']).items())),'prompt_tokens':{'minimum':min(tokens),'mean':sum(tokens)/len(tokens),'maximum':max(tokens),'cap':c['max_input_tokens']},'hashes':{'contract':H(cp),'prompt_manifest':H(mp),'adjudication_manifest':H(lp),'harvest':H(hp),'execution_lock':H(ep),'source':H(Path(__file__))},'gpu_status':'blocked_external_pid_2190159_on_gpu_2_3','model_outcomes_observed':False,'dev_or_test_read':False,'protected_local_only':True,'headline_eligible':False};(out/'manifest_audit.json').write_text(json.dumps(payload,indent=2,sort_keys=True)+'\n');lines=['# AppWorld A3 — Semantic Write-Signal Manifest','',f"## Status: **`{status}`**",'',f"- Strict live/dead pairs: {len(pairs)}",f"- Frozen prompts: {len(rows)}",f"- Independent train task types: {payload['task_types']}",f"- Formatted prompt tokens: {payload['prompt_tokens']['minimum']}–{payload['prompt_tokens']['maximum']} (mean {payload['prompt_tokens']['mean']:.1f})",'- Frozen runner/analyzer: included in execution lock','- Model outcomes observed: No','- GPU 2/3: blocked by external PID 2190159','- Dev/test read: No','- Protected benchmark content: local-only, not for redistribution','','## Checks','']+[f"- `{k}`: **{'PASS' if v else 'FAIL'}**" for k,v in checks.items()]+['','Every dead proposal is a successful write followed by a fully successful unchanged suffix and a failed official evaluator. This is a pre-commit signal anchor, not an end-to-end task-completion result.'];(out/'MANIFEST.md').write_text('\n'.join(lines)+'\n');print(json.dumps({'status':status,'pairs':len(pairs),'prompts':len(rows),'report':str((out/'MANIFEST.md').relative_to(REPO_ROOT))}))
if __name__=='__main__':main()
