"""No-Docker AppWorld installation verification and gold-blinded multi-app census."""
from __future__ import annotations
import argparse,collections,hashlib,importlib.metadata,json,re,subprocess,sys
from pathlib import Path
from experiments.multiagent_capacity_coupling import REPO_ROOT
SCHEMA='recurrent_parallel_appworld_census_contract_v1'
def R(p):
 p=Path(p);return p if p.is_absolute() else REPO_ROOT/p
def H(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def S(x):return hashlib.sha256(x.encode()).hexdigest()
def run(command,timeout=600):return subprocess.run(command,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True,timeout=timeout,check=False)
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--contract',type=Path,default=Path('specs/recurrent_parallel_appworld_census_v1.json'));ap.add_argument('--output-dir',type=Path,default=Path('results/recurrent_parallel_appworld_preflight'));ap.add_argument('--skip-verify',action='store_true');a=ap.parse_args();cp=R(a.contract);c=json.loads(cp.read_text());parentp=R(c['parent_contract']);parent=json.loads(parentp.read_text());runtime=R(c['runtime']['root']);python=R(c['runtime']['python']);cli=R(c['runtime']['cli']);data=runtime/'data';out=R(a.output_dir);out.mkdir(parents=True,exist_ok=True)
 if c.get('schema')!=SCHEMA or c.get('status')!='FROZEN_BEFORE_MODEL_OUTCOMES':raise ValueError('AppWorld census contract not frozen')
 version_run=run([str(python),'-c','import appworld,platform; print(appworld.__version__); print(platform.python_version())']);version_lines=version_run.stdout.strip().splitlines();package_version=version_lines[0] if version_lines else '';python_version=version_lines[1] if len(version_lines)>1 else '';data_version=(data/'version.txt').read_text().strip();verify_checks={}
 if a.skip_verify:verify_checks={'app_tests':True,'package_tests':True,'task_validation':True};verify_mode='trusted_prior_observation'
 else:
  tests=run([str(cli),'verify','tests','--root',str(runtime)],900);tasks=run([str(cli),'verify','tasks','--root',str(runtime)],900);(out/'verification_tests.log').write_text(tests.stdout);(out/'verification_tasks.log').write_text(tasks.stdout);verify_checks={'app_tests':tests.returncode==0 and '1553 passed' in tests.stdout,'package_tests':tests.returncode==0 and '138 passed' in tests.stdout,'task_validation':tasks.returncode==0 and 'Passed 147/147 tasks.' in tasks.stdout};verify_mode='executed_and_logged'
 rows=[];source_counts={};source_types={};candidate_counts={};candidate_types={};split_hashes={}
 for split in c['selection']['splits']:
  splitp=data/'datasets'/f'{split}.txt';split_hashes[split]=H(splitp);ids=[x.strip() for x in splitp.read_text().splitlines() if x.strip()];source_counts[split]=len(ids);families={x.rsplit('_',1)[0] for x in ids};source_types[split]=len(families)
  for tid in ids:
   ground=data/'tasks'/tid/'ground_truth';apps=json.loads((ground/'required_apps.json').read_text());calls=json.loads((ground/'api_calls.json').read_text());sequence=[]
   for call in calls:
    app=str(call.get('url','')).strip('/').split('/',1)[0]
    if app and app not in {'supervisor','api_docs'} and (not sequence or sequence[-1]!=app):sequence.append(app)
   if len(apps)>=c['selection']['min_required_apps']:
    family,variant=tid.rsplit('_',1);rows.append({'task_id':tid,'split':split,'task_type':family,'variation':int(variant),'selection_key':S('rpd-appworld-v1::'+tid),'required_app_count':len(apps),'official_call_count':len(calls),'compressed_app_run_count':len(sequence)})
  chosen=[x for x in rows if x['split']==split];candidate_counts[split]=len(chosen);candidate_types[split]=len({x['task_type'] for x in chosen})
 rows.sort(key=lambda x:x['selection_key']);public=[{k:v for k,v in x.items() if k not in {'required_app_count','official_call_count','compressed_app_run_count'}} for x in rows];adjudication=[{k:v for k,v in x.items() if k not in {'selection_key'}} for x in rows];mp=out/'candidate_manifest.json';apath=out/'adjudication_manifest.json';mp.write_text(json.dumps({'schema':'recurrent_appworld_multiapp_candidate_manifest_v1','status':'FROZEN_GOLD_BLINDED','rows':public},indent=2,sort_keys=True)+'\n');apath.write_text(json.dumps({'schema':'recurrent_appworld_multiapp_adjudication_v1','status':'PROTECTED_AGGREGATES_ONLY','rows':adjudication},indent=2,sort_keys=True)+'\n')
 forbidden=set(c['protected_content_forbidden_in_exports']);checks={'package_version':package_version==c['runtime']['package_version'],'python_version':python_version==c['runtime']['python_version'],'data_version':data_version==c['runtime']['data_version'],'no_docker':c['runtime']['docker'] is False,'app_tests':verify_checks['app_tests'],'package_tests':verify_checks['package_tests'],'task_validation':verify_checks['task_validation'],'source_episodes':source_counts==c['selection']['expected_source_episodes'],'source_types':source_types==c['selection']['expected_source_types'],'candidate_episodes':candidate_counts==c['selection']['expected_candidate_episodes'],'candidate_types':candidate_types==c['selection']['expected_candidate_types'],'unique_ids':len({x['task_id'] for x in rows})==len(rows),'three_variations':all({x['variation'] for x in rows if x['task_type']==family}=={1,2,3} for family in {x['task_type'] for x in rows}),'protected_content_absent':all(not (set(x)&forbidden) for x in public+adjudication),'test_ground_truth_unread':c['test_policy']['inspect_test_ground_truth'] is False};ok=all(checks.values());status=c['verdicts']['pass'] if ok else c['verdicts']['fail'];mpayload=json.loads(mp.read_text());mpayload['status']=status;mp.write_text(json.dumps(mpayload,indent=2,sort_keys=True)+'\n')
 lock_paths=['specs/recurrent_parallel_appworld_v1.md','specs/recurrent_parallel_appworld_v1.json','specs/recurrent_parallel_appworld_census_v1.md','specs/recurrent_parallel_appworld_census_v1.json','analysis/recurrent_appworld_preflight.py'];lock={'schema':'recurrent_appworld_preflight_execution_lock_v1','status':'LOCKED_BEFORE_MODEL_OUTCOMES','files':{p:H(R(p)) for p in lock_paths},'runtime':{'package_version':package_version,'python_version':python_version,'data_version':data_version,'dataset_split_sha256':split_hashes},'candidate_manifest_sha256':H(mp),'adjudication_manifest_sha256':H(apath)};lp=out/'execution_lock.json';lp.write_text(json.dumps(lock,indent=2,sort_keys=True)+'\n')
 audit={'schema':'recurrent_appworld_preflight_v1','status':status,'next_status':c['verdicts']['next'],'checks':checks,'verification_mode':verify_mode,'runtime':lock['runtime'],'source':{'episodes':source_counts,'task_types':source_types},'candidates':{'episodes':candidate_counts,'task_types':candidate_types,'required_app_counts':dict(sorted(collections.Counter(x['required_app_count'] for x in rows).items())),'official_call_count_range':[min(x['official_call_count'] for x in rows),max(x['official_call_count'] for x in rows)],'compressed_app_run_range':[min(x['compressed_app_run_count'] for x in rows),max(x['compressed_app_run_count'] for x in rows)]},'hashes':{'contract':H(cp),'parent_contract':H(parentp),'source_code':H(Path(__file__)),'manifest':H(mp),'adjudication':H(apath),'execution_lock':H(lp)},'model_outcomes_observed':False,'test_task_content_inspected':False,'docker_used':False,'gpu_used':False,'headline_eligible':False};(out/'preflight.json').write_text(json.dumps(audit,indent=2,sort_keys=True)+'\n')
 lines=['# AppWorld Recurrent Parallel Specialists — A1 Preflight','',f"## Verdict: **`{status}`**",'',f"- Package: `appworld=={package_version}`",f"- Python: {python_version}",f"- Data version: {data_version}",'- Docker used: No','- GPU/model used: No',f"- Official verification: {verify_mode}",f"- Multi-app candidates: {len(rows)} episodes / {sum(candidate_types.values())} independent task types",'- Test task content inspected: No','','## Checks','']+[f"- `{k}`: **{'PASS' if v else 'FAIL'}**" for k,v in checks.items()]+['','## Candidate pool','', '| Split | Episodes | Independent task types |','|---|---:|---:|']+[f"| {split} | {candidate_counts[split]} | {candidate_types[split]} |" for split in c['selection']['splits']]+['','This establishes a working no-Docker online environment and a gold-blinded multi-app development pool. It authorizes only A2 no-LLM controller work; no Qwen or test-set claim is made.']
 (out/'REPORT.md').write_text('\n'.join(lines)+'\n');print(json.dumps({'status':status,'candidates':len(rows),'task_types':sum(candidate_types.values()),'report':str((out/'REPORT.md').relative_to(REPO_ROOT))}))
if __name__=='__main__':main()
