"""Audit and lock AppWorld A4 comparative prompts before model outcomes."""
from __future__ import annotations
import argparse,hashlib,json,re
from pathlib import Path
from analysis.recurrent_appworld_a3_run import H,R
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--contract',type=Path,default=Path('specs/recurrent_parallel_appworld_comparative_development_v1.json'));ap.add_argument('--output-dir',type=Path,default=Path('results/recurrent_parallel_appworld_comparative_development'));a=ap.parse_args();cp=R(a.contract);c=json.loads(cp.read_text());out=R(a.output_dir);mp=out/'prompt_manifest.json';lp=out/'adjudication_manifest.json';mapath=out/'manifest.json';m=json.loads(mp.read_text());labels=json.loads(lp.read_text());ma=json.loads(mapath.read_text());rows=m['rows'];by={(x['pair_id'],x['arm'],x['order']):x for x in rows};swap=True;arm_match=True
 for pair in {x['pair_id'] for x in rows}:
  for arm in c['arms']:
   ab=json.loads(by[(pair,arm,'AB')]['prompt'].splitlines()[-1]);ba=json.loads(by[(pair,arm,'BA')]['prompt'].splitlines()[-1]);swap=swap and ab['candidate_A_arguments']==ba['candidate_B_arguments'] and ab['candidate_B_arguments']==ba['candidate_A_arguments'];ab_shared={k:v for k,v in ab.items() if not k.startswith('candidate_A') and not k.startswith('candidate_B')};ba_shared={k:v for k,v in ba.items() if not k.startswith('candidate_A') and not k.startswith('candidate_B')};swap=swap and ab_shared==ba_shared
  c1=json.loads(by[(pair,'C1_comparative_local','AB')]['prompt'].splitlines()[-1]);c2=json.loads(by[(pair,'C2_comparative_provenance','AB')]['prompt'].splitlines()[-1]);arm_match=arm_match and c1['candidate_A_arguments']==c2['candidate_A_arguments'] and c1['candidate_B_arguments']==c2['candidate_B_arguments'] and all(c1[k]==c2[k] for k in c1 if k not in ('candidate_A_arguments','candidate_B_arguments'))
 from transformers import AutoTokenizer
 tok=AutoTokenizer.from_pretrained(c['model'],revision=c['model_revision'],local_files_only=True);tokens=[]
 for row in rows:
  text=tok.apply_chat_template([{'role':'system','content':'Choose the better pre-commit candidate and output only JSON.'},{'role':'user','content':row['prompt']}],tokenize=False,add_generation_prompt=True,enable_thinking=c['enable_thinking']);tokens.append(len(tok(text)['input_ids']))
 forbidden=('password','access_token','card_number','cvv_number','ground_truth','evaluator');checks={'source_manifest':ma['status']=='APPWORLD_A4_MANIFEST_COMPLETE' and all(ma['checks'].values()),'cardinality':len(rows)==c['expected_prompts'],'unique_prompts':len({x['prompt_sha256'] for x in rows})==len(rows),'prompt_hashes':all(hashlib.sha256(x['prompt'].encode()).hexdigest()==x['prompt_sha256'] for x in rows),'exact_label_ids':{x['sample_id'] for x in rows}=={x['sample_id'] for x in labels['rows']},'exact_swaps':swap,'arm_context_match':arm_match,'input_cap':max(tokens)<=c['max_input_tokens'],'forbidden_absent':all(not any(v in x['prompt'].lower() for v in forbidden) for x in rows),'jwt_absent':all(not re.search(r'eyJ[A-Za-z0-9_-]{20,}',x['prompt']) for x in rows),'raw_absent':not (out/'raw_model_outputs.json').exists()};
 if not all(checks.values()):raise RuntimeError(checks)
 files=['specs/recurrent_parallel_appworld_comparative_development_v1.md','specs/recurrent_parallel_appworld_comparative_development_v1.json','experiments/appworld_provenance.py','experiments/appworld_trace_replay.py','analysis/recurrent_appworld_a4_manifest.py','analysis/recurrent_appworld_a4_preflight.py','analysis/recurrent_appworld_a4_run.py','analysis/recurrent_appworld_a4_analysis.py','results/recurrent_parallel_appworld_signal_anchor/prompt_manifest.json','results/recurrent_parallel_appworld_signal_anchor/adjudication_manifest.json','results/recurrent_parallel_appworld_signal_anchor/contended_analysis.json','results/model_download/qwen3_5_4b/qwen_download.json'];lock={'schema':'recurrent_appworld_a4_execution_lock_v1','status':'LOCKED_BEFORE_MODEL_OUTCOMES','files':{p:H(R(p)) for p in files},'contract_sha256':H(cp),'prompt_manifest_sha256':H(mp),'adjudication_manifest_sha256':H(lp)};lockp=out/'execution_lock.json';lockp.write_text(json.dumps(lock,indent=2,sort_keys=True)+'\n');payload={'schema':'recurrent_appworld_a4_preflight_v1','status':'RPD_APPWORLD_A4_EXECUTION_READY','checks':checks,'pairs':c['expected_pairs'],'prompts':len(rows),'prompt_tokens':{'min':min(tokens),'mean':sum(tokens)/len(tokens),'max':max(tokens)},'deterministic_provenance':{k:v for k,v in ma['deterministic_provenance'].items() if k!='rows'},'hashes':{'contract':H(cp),'manifest':H(mp),'labels':H(lp),'execution_lock':H(lockp),'source':H(Path(__file__))},'model_outcomes_observed':False,'train_only':True,'headline_eligible':False};(out/'preflight.json').write_text(json.dumps(payload,indent=2,sort_keys=True)+'\n');lines=['# AppWorld A4 — Comparative Evidence Preflight','',f"## Status: **`{payload['status']}`**",'',f"- Matched pairs: {c['expected_pairs']}",f"- Frozen prompts: {len(rows)}",f"- Prompt tokens: {min(tokens)}–{max(tokens)}",f"- Deterministic provenance coverage: {payload['deterministic_provenance']['coverage']:.3f}",f"- Deterministic covered accuracy: {payload['deterministic_provenance']['covered_accuracy']:.3f}",'- New model outcomes: No','- Train development only: Yes','','## Checks','']+[f"- `{k}`: **{'PASS' if v else 'FAIL'}**" for k,v in checks.items()];(out/'MANIFEST.md').write_text('\n'.join(lines)+'\n');print(json.dumps({'status':payload['status'],'prompts':len(rows),'report':str((out/'MANIFEST.md').relative_to(R('.')))}))
if __name__=='__main__':main()
