"""Authoritative replay-label erratum for the locked joint cost-sensitive analysis."""
from __future__ import annotations
import json, hashlib
from pathlib import Path
from analysis.recurrent_parallel_cost_sensitive_run import verify_lock
from experiments.multiagent_capacity_coupling import REPO_ROOT
from experiments.recurrent_parallel_core import run_noisy_recurrent_correction
from experiments.recurrent_parallel_sat_core import run_noisy_sat_recurrence

def H(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 root=REPO_ROOT; lp=root/'specs/recurrent_parallel_cost_sensitive_execution_lock_v1.json';lock,checks=verify_lock(lp);rp=root/'results/recurrent_parallel_cost_sensitive_confirmation/raw_results.json';ap=root/'results/recurrent_parallel_cost_sensitive_confirmation/analysis.json';raw=json.loads(rp.read_text());original=json.loads(ap.read_text());c=json.loads((root/lock['files']['contract_json']['path']).read_text());gm={r['instance_id']:r for r in json.loads((root/lock['files']['graph_manifest']['path']).read_text())['rows']};sm={r['instance_id']:r for r in json.loads((root/lock['files']['sat_manifest']['path']).read_text())['rows']}
 targets=[r for r in raw['rows'] if r['system']=='R_adaptive'][:16];details=[]
 for x in targets:
  fn=run_noisy_recurrent_correction if x['substrate']=='graph' else run_noisy_sat_recurrence;inst=(gm if x['substrate']=='graph' else sm)[x['instance_id']];k=c['schedule'][x['substrate']][str(x['partition_diameter'])][str(float(x['eta_fp']))];rr=fn(inst,system='R_adaptive',eta_fp=x['eta_fp'],round_cap=32,noise_seed=c['noise_seed'],confirmation_hits=k);before=[key for key in sorted(set(rr)|set(x)) if rr.get(key)!=x.get(key)];rr['substrate']=x['substrate'];after=[key for key in sorted(set(rr)|set(x)) if rr.get(key)!=x.get(key)];details.append({'instance_id':x['instance_id'],'eta_fp':x['eta_fp'],'differences_before_runner_metadata':before,'differences_after_runner_metadata':after})
 corrected_replay=sum(bool(x['differences_after_runner_metadata']) for x in details);j0=raw['status']=='RPD_COST_SENSITIVE_RAW_COMPLETE' and all(raw['cardinality'].values()) and all(raw['semantics'].values()) and all(checks.values()) and len(details)>=16 and corrected_replay==0;gates=dict(original['gates']);gates['J0_integrity']=j0;status='RPD_COST_SENSITIVE_CROSS_SUBSTRATE_CONFIRMATION_PASS' if all(gates.values()) else original['status']
 p={'schema':'cost_sensitive_joint_analysis_erratum_v1','frozen_analysis_status':original['status'],'corrected_status':status,'field':'replay comparison normalization','reason':'Raw runner appends a substrate label after engine execution; frozen replay compared the unlabeled engine row to the labeled raw row. Restoring the deterministic runner metadata removes all 16 mismatches.','raw_sha256':H(rp),'frozen_analysis_sha256':H(ap),'execution_lock_sha256':H(lp),'lock_checks':checks,'replay_rows':len(details),'frozen_replay_mismatches':16,'corrected_replay_mismatches':corrected_replay,'only_frozen_difference':'substrate','gates':gates,'details':details,'other_statistics_changed':False}
 out=root/'results/recurrent_parallel_cost_sensitive_confirmation';(out/'analysis_erratum.json').write_text(json.dumps(p,indent=2,sort_keys=True)+'\n');lines=['# Joint Cost-Sensitive Analysis Erratum','',f"- Frozen analysis verdict: **`{original['status']}`**",f"- Corrected verdict: **`{status}`**",'- Raw rows rerun: **No**','- Non-replay statistics changed: **No**','','## Correction','','The frozen replay helper compared an engine-returned row with the raw runner output. The runner adds the deterministic `substrate` field after engine execution. All 16 frozen replay differences were exactly this metadata field. After restoring the runner-added label, replay mismatches are 0/16.','','## Corrected gates','']+[f"- `{k}`: **{'PASS' if v else 'FAIL'}**" for k,v in gates.items()]+['','The immutable raw artifact and frozen analysis remain preserved. This erratum is authoritative for the replay-integrity gate and final verdict.',''];(out/'ANALYSIS_ERRATUM.md').write_text('\n'.join(lines));print(json.dumps({'status':status,'corrected_replay_mismatches':corrected_replay,'report':'results/recurrent_parallel_cost_sensitive_confirmation/ANALYSIS_ERRATUM.md'}))
if __name__=='__main__':main()
