"""Parser-only repair of AppWorld A1 official-verifier capture semantics."""
from __future__ import annotations
import argparse,hashlib,json,re,subprocess
from pathlib import Path
from experiments.multiagent_capacity_coupling import REPO_ROOT
SCHEMA='recurrent_parallel_appworld_census_contract_v2'
def R(p):
 p=Path(p);return p if p.is_absolute() else REPO_ROOT/p
def H(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def run(command):return subprocess.run(command,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True,timeout=900,check=False)
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--contract',type=Path,default=Path('specs/recurrent_parallel_appworld_census_v2.json'));ap.add_argument('--output-dir',type=Path,default=Path('results/recurrent_parallel_appworld_preflight_v2'));a=ap.parse_args();cp=R(a.contract);c=json.loads(cp.read_text());v1p=R(c['v1_preflight']);v1=json.loads(v1p.read_text());v1mp=R(c['v1_candidate_manifest']);v1ap=R(c['v1_adjudication_manifest']);oldm=json.loads(v1mp.read_text());olda=json.loads(v1ap.read_text());runtime=R(c['runtime']['root']);cli=R(c['runtime']['cli']);out=R(a.output_dir);out.mkdir(parents=True,exist_ok=True)
 if c.get('schema')!=SCHEMA or c.get('status')!='FROZEN_BEFORE_MODEL_OUTCOMES':raise ValueError('v2 parser contract not frozen')
 false_checks=sorted(k for k,v in v1['checks'].items() if not v);tests=run([str(cli),'verify','tests','--root',str(runtime)]);tasks=run([str(cli),'verify','tasks','--root',str(runtime)]);(out/'verification_tests.log').write_text(tests.stdout);(out/'verification_tasks.log').write_text(tasks.stdout);failure_pattern=re.compile(r'\b[1-9][0-9]* failed\b|\bERRORS?\b');parsed={'app_tests':tests.returncode==0 and '1553 passed' in tests.stdout,'package_tests':tests.returncode==0 and 'collected 138 items' in tests.stdout and 'test_appworld.py' in tests.stdout and '[100%]' in tests.stdout and not failure_pattern.search(tests.stdout),'task_validation':tasks.returncode==0 and '147/147' in tasks.stdout}
 checks={**v1['checks'],**parsed,'v1_failure_preserved':v1['status']=='RPD_APPWORLD_A1_PREFLIGHT_FAIL','v1_false_checks_exact':false_checks==sorted(c['expected_v1_false_checks']),'repair_before_model_outcomes':c['model_outcomes_observed_before_repair'] is False};ok=all(checks.values());status=c['verdicts']['pass'] if ok else c['verdicts']['fail'];newm={**oldm,'schema':'recurrent_appworld_multiapp_candidate_manifest_v2','status':status};newa={**olda,'schema':'recurrent_appworld_multiapp_adjudication_v2','status':'PROTECTED_AGGREGATES_ONLY'};mp=out/'candidate_manifest.json';adp=out/'adjudication_manifest.json';mp.write_text(json.dumps(newm,indent=2,sort_keys=True)+'\n');adp.write_text(json.dumps(newa,indent=2,sort_keys=True)+'\n');checks['candidate_rows_unchanged']=newm['rows']==oldm['rows'];checks['adjudication_rows_unchanged']=newa['rows']==olda['rows'];ok=all(checks.values());status=c['verdicts']['pass'] if ok else c['verdicts']['fail'];newm['status']=status;mp.write_text(json.dumps(newm,indent=2,sort_keys=True)+'\n')
 lock_paths=['specs/recurrent_parallel_appworld_census_v2.md','specs/recurrent_parallel_appworld_census_v2.json','analysis/recurrent_appworld_preflight_v2.py',c['v1_preflight'],c['v1_candidate_manifest'],c['v1_adjudication_manifest']];lock={'schema':'recurrent_appworld_preflight_execution_lock_v2','status':'LOCKED_BEFORE_MODEL_OUTCOMES','files':{p:H(R(p)) for p in lock_paths},'candidate_manifest_sha256':H(mp),'adjudication_manifest_sha256':H(adp),'verifier_log_sha256':{'tests':H(out/'verification_tests.log'),'tasks':H(out/'verification_tasks.log')}};lp=out/'execution_lock.json';lp.write_text(json.dumps(lock,indent=2,sort_keys=True)+'\n')
 audit={'schema':'recurrent_appworld_preflight_v2','status':status,'next_status':c['verdicts']['next'],'repair_scope':c['repair_scope'],'v1':{'status':v1['status'],'false_checks':false_checks,'sha256':H(v1p)},'verifier':{'tests_returncode':tests.returncode,'tasks_returncode':tasks.returncode,'rules':parsed},'checks':checks,'candidates':v1['candidates'],'source':v1['source'],'runtime':v1['runtime'],'hashes':{'contract':H(cp),'source_code':H(Path(__file__)),'candidate_manifest':H(mp),'adjudication_manifest':H(adp),'execution_lock':H(lp)},'model_outcomes_observed':False,'test_task_content_inspected':False,'docker_used':False,'gpu_used':False,'headline_eligible':False};(out/'preflight.json').write_text(json.dumps(audit,indent=2,sort_keys=True)+'\n');lines=['# AppWorld Recurrent Parallel Specialists — A1 Preflight v2','',f"## Verdict: **`{status}`**",'',f"- v1 preserved verdict: `{v1['status']}`",f"- Repair scope: {c['repair_scope']}",f"- Tests verifier return code: {tests.returncode}",f"- Tasks verifier return code: {tasks.returncode}",f"- Multi-app candidates: {sum(v1['candidates']['episodes'].values())} episodes / {sum(v1['candidates']['task_types'].values())} independent task types",'- Model/GPU/Docker used: No','- Test task content inspected: No','','## Checks','']+[f"- `{k}`: **{'PASS' if v else 'FAIL'}**" for k,v in checks.items()]+['','## Candidate pool','', '| Split | Episodes | Independent task types |','|---|---:|---:|']+[f"| {split} | {v1['candidates']['episodes'][split]} | {v1['candidates']['task_types'][split]} |" for split in ('train','dev')]+['','A pass establishes the no-Docker online environment and authorizes A2 no-LLM recurrent controller work. It does not authorize a Qwen or test-set claim.'];(out/'REPORT.md').write_text('\n'.join(lines)+'\n');print(json.dumps({'status':status,'candidates':sum(v1['candidates']['episodes'].values()),'task_types':sum(v1['candidates']['task_types'].values()),'report':str((out/'REPORT.md').relative_to(REPO_ROOT))}))
if __name__=='__main__':main()
