"""Read-only container-runtime readiness audit for the real-code benchmark."""
from __future__ import annotations
import argparse,hashlib,json,os,shutil,socket,subprocess
from datetime import datetime,timezone
from pathlib import Path
from experiments.multiagent_capacity_coupling import REPO_ROOT
RUNTIMES=('docker','podman','apptainer','singularity','enroot','nerdctl','buildah','crictl','ctr','containerd')
SOCKETS=('/var/run/docker.sock','/run/containerd/containerd.sock','/run/podman/podman.sock')
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--output-dir',type=Path,default=Path('results/recurrent_parallel_real_code_container_readiness'));a=ap.parse_args();out=a.output_dir if a.output_dir.is_absolute() else REPO_ROOT/a.output_dir;out.mkdir(parents=True,exist_ok=True);binaries={x:shutil.which(x) for x in RUNTIMES};sockets={x:Path(x).exists() for x in SOCKETS};docker_server=False;docker_detail='client not installed'
 if binaries['docker']:
  p=subprocess.run([binaries['docker'],'version','--format','{{.Server.Version}}'],capture_output=True,text=True,timeout=15,check=False);docker_server=p.returncode==0 and bool(p.stdout.strip());docker_detail=p.stdout.strip() if docker_server else (p.stderr.strip() or f'exit={p.returncode}')
 disk=shutil.disk_usage('/');alternatives=[x for x in RUNTIMES[1:] if binaries[x]];ready=bool(binaries['docker'] and sockets['/var/run/docker.sock'] and docker_server);status='RPD_REAL_CODE_DOCKER_READY' if ready else ('RPD_REAL_CODE_ALTERNATIVE_RUNTIME_REVIEW' if alternatives else 'RPD_REAL_CODE_DOCKER_UNAVAILABLE');payload={'schema':'recurrent_real_code_container_readiness_v1','status':status,'generated_at':datetime.now(timezone.utc).isoformat(),'hostname':socket.gethostname(),'uid':os.getuid(),'gid':os.getgid(),'groups':os.getgroups(),'binaries':binaries,'sockets':sockets,'docker_server_reachable':docker_server,'docker_detail':docker_detail,'alternative_runtimes':alternatives,'disk':{'total_bytes':disk.total,'used_bytes':disk.used,'free_bytes':disk.free},'checks':{'docker_client':binaries['docker'] is not None,'docker_socket':sockets['/var/run/docker.sock'],'docker_daemon':docker_server,'disk_free_at_least_500_gib':disk.free>=500*1024**3},'benchmark_stages':{'B0_structural':'READY_NO_DOCKER_REQUIRED','B1_operational':'READY' if ready else 'BLOCKED_DOCKER_REQUIRED','B2_exact_labels':'READY' if ready else 'BLOCKED_BY_B1','B3_qwen_judge':'BLOCKED_BY_B2','B4_mechanism':'BLOCKED_BY_B2','B5_end_to_end':'BLOCKED_BY_B1'},'external_processes_modified':False,'source_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest()};(out/'readiness.json').write_text(json.dumps(payload,indent=2,sort_keys=True)+'\n');lines=['# Real-Code Benchmark — Container Readiness','',f"## Status: **`{status}`**",'',f"- Docker client: {'available' if binaries['docker'] else 'not found'}",f"- Docker socket: {'available' if sockets['/var/run/docker.sock'] else 'not found'}",f"- Docker daemon reachable: {'yes' if docker_server else 'no'}",f"- Alternative runtime: {', '.join(alternatives) if alternatives else 'none found'}",f"- Free filesystem capacity: {disk.free/1024**4:.2f} TiB",'- Containers/images created: No','- External processes modified: No','','## Stage impact','', '| Stage | Status |','|---|---|']+[f'| {k} | `{v}` |' for k,v in payload['benchmark_stages'].items()]+['','## Conclusion','','This server cannot currently execute the official Multi-SWE Docker harness. Installing the Python `docker` package is insufficient because both the client binary and daemon/socket are absent. B0 remains valid; B1–B5 must wait for an administrator-provided Docker Engine/socket or run on another Docker-capable host. Docker-group access is security-equivalent to privileged host access and should be provisioned by the server administrator, not bypassed by the experiment.'];(out/'REPORT.md').write_text('\n'.join(lines)+'\n');print(json.dumps({'status':status,'report':str((out/'REPORT.md').relative_to(REPO_ROOT)),'free_tib':round(disk.free/1024**4,2)}))
if __name__=='__main__':main()
