"""Lock the explicitly authorized quality-only shared-GPU AppWorld A3 route."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from analysis.recurrent_appworld_a3_run import H,R,verify_lock
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--addendum',type=Path,default=Path('specs/recurrent_parallel_appworld_signal_contended_execution_v1.json'));ap.add_argument('--output-dir',type=Path,default=Path('results/recurrent_parallel_appworld_signal_anchor'));a=ap.parse_args();apath=R(a.addendum);add=json.loads(apath.read_text());parentp=R(add['parent_contract']);parent=json.loads(parentp.read_text());parentlockp=R(add['parent_execution_lock']);_,parent_checks=verify_lock(parentlockp);out=R(a.output_dir);rawp=out/'raw_model_outputs.json';files=['specs/recurrent_parallel_appworld_signal_contended_execution_v1.md','specs/recurrent_parallel_appworld_signal_contended_execution_v1.json','analysis/recurrent_appworld_a3_contended_preflight.py','analysis/recurrent_appworld_a3_contended_run.py','analysis/recurrent_appworld_a3_analysis.py','analysis/recurrent_appworld_a3_contended_analysis.py'];checks={'addendum_frozen':add['status']=='FROZEN_BEFORE_MODEL_OUTCOMES','parent_frozen':parent['status']=='FROZEN_BEFORE_PROMPTS_AND_MODEL_OUTCOMES','parent_lock_files':all(parent_checks.values()),'user_authorized':add['user_authorized_shared_gpu'] is True,'latency_excluded':add['latency_authoritative'] is False,'raw_absent':not rawp.exists(),'files_exist':all(R(x).exists() for x in files)}
 if not all(checks.values()):raise RuntimeError(checks)
 lock={'schema':'recurrent_appworld_a3_contended_execution_lock_v1','status':'LOCKED_BEFORE_MODEL_OUTCOMES','files':{p:H(R(p)) for p in files},'parent_execution_lock_path':add['parent_execution_lock'],'parent_execution_lock_sha256':H(parentlockp),'parent_contract_sha256':H(parentp),'addendum_contract_sha256':H(apath),'physical_gpu':add['physical_gpu'],'memory_fraction_cap':add['memory_fraction_cap'],'quality_only':True};lp=out/'contended_execution_lock.json';lp.write_text(json.dumps(lock,indent=2,sort_keys=True)+'\n');payload={'schema':'recurrent_appworld_a3_contended_preflight_v1','status':'RPD_APPWORLD_A3_CONTENDED_EXECUTION_READY','checks':checks,'hashes':{'addendum':H(apath),'parent_lock':H(parentlockp),'execution_lock':H(lp),'source':H(Path(__file__))},'model_outcomes_observed':False,'external_process_actions_taken':False};(out/'contended_preflight.json').write_text(json.dumps(payload,indent=2,sort_keys=True)+'\n');lines=['# AppWorld A3 — Contended Quality-Only Execution Preflight','',f"## Status: **`{payload['status']}`**",'',f"- Physical GPU: {add['physical_gpu']}",f"- Per-process memory fraction cap: {add['memory_fraction_cap']:.2f}",'- Signal quality: authorized','- Token counts: authorized','- Latency/throughput: non-authoritative','- External process actions: forbidden and none taken','','## Checks','']+[f"- `{k}`: **{'PASS' if v else 'FAIL'}**" for k,v in checks.items()];(out/'CONTENDED_PREFLIGHT.md').write_text('\n'.join(lines)+'\n');print(json.dumps({'status':payload['status'],'lock':str(lp.relative_to(R('.')))}))
if __name__=='__main__':main()
